-- Schema Oracle pentru proiectul PAO/PAOJ aibilet - Etapa II
-- Script rerulabil in Oracle SQL Developer.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE comanda_bilete CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE agent_event_assignments CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE comenzi CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE bilete CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE locuri_eveniment CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE tipuri_bilete_eveniment CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE evenimente CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE locatii CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE utilizatori CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE utilizatori (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    rol VARCHAR2(30) NOT NULL,
    username VARCHAR2(60) NOT NULL,
    parola VARCHAR2(120) NOT NULL,
    nume VARCHAR2(80) NOT NULL,
    prenume VARCHAR2(80) NOT NULL,
    email VARCHAR2(120) NOT NULL,
    telefon VARCHAR2(30) NOT NULL,
    nume_organizatie VARCHAR2(200),
    CONSTRAINT pk_utilizatori PRIMARY KEY (id),
    CONSTRAINT uq_utilizatori_username UNIQUE (username),
    CONSTRAINT uq_utilizatori_email UNIQUE (email),
    CONSTRAINT ck_utilizatori_rol CHECK (rol IN ('CLIENT', 'ORGANIZATOR', 'ADMIN', 'AGENT_CHECK_IN')),
    CONSTRAINT ck_utilizatori_org CHECK (
        (rol = 'ORGANIZATOR' AND nume_organizatie IS NOT NULL)
        OR (rol <> 'ORGANIZATOR')
    )
);

CREATE TABLE locatii (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    denumire VARCHAR2(160) NOT NULL,
    oras VARCHAR2(100) NOT NULL,
    adresa VARCHAR2(250) NOT NULL,
    suporta_locuri NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_locatii PRIMARY KEY (id),
    CONSTRAINT ck_locatii_suporta_locuri CHECK (suporta_locuri IN (0, 1))
);

CREATE TABLE evenimente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    tip_eveniment VARCHAR2(20) NOT NULL,
    titlu VARCHAR2(180) NOT NULL,
    descriere VARCHAR2(2000) NOT NULL,
    categorie VARCHAR2(30) NOT NULL,
    data_ora_inceput TIMESTAMP NOT NULL,
    data_ora_final TIMESTAMP NOT NULL,
    status VARCHAR2(20) NOT NULL,
    locatie_id NUMBER NOT NULL,
    organizator_id NUMBER NOT NULL,
    nume_organizatie_organizator VARCHAR2(200) NOT NULL,
    CONSTRAINT pk_evenimente PRIMARY KEY (id),
    CONSTRAINT fk_evenimente_locatie FOREIGN KEY (locatie_id) REFERENCES locatii(id),
    CONSTRAINT fk_evenimente_organizator FOREIGN KEY (organizator_id) REFERENCES utilizatori(id),
    CONSTRAINT ck_evenimente_tip CHECK (tip_eveniment IN ('SEATED', 'STANDING')),
    CONSTRAINT ck_evenimente_categorie CHECK (categorie IN (
        'CONCERT', 'FESTIVAL', 'TEATRU', 'FILM', 'STAND_UP', 'CONFERINTA',
        'OPERA', 'SPORT', 'EXPOZITIE', 'PARTY', 'ALTUL'
    )),
    CONSTRAINT ck_evenimente_status CHECK (status IN ('PROGRAMAT', 'ANULAT', 'SOLD_OUT')),
    CONSTRAINT ck_evenimente_interval CHECK (data_ora_final >= data_ora_inceput)
);

CREATE TABLE tipuri_bilete_eveniment (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    eveniment_id NUMBER NOT NULL,
    nume VARCHAR2(80) NOT NULL,
    pret NUMBER(10, 2) NOT NULL,
    stoc_total NUMBER(8) DEFAULT 0 NOT NULL,
    stoc_disponibil NUMBER(8) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_tipuri_bilete_eveniment PRIMARY KEY (id),
    CONSTRAINT fk_tipuri_bilete_eveniment FOREIGN KEY (eveniment_id) REFERENCES evenimente(id) ON DELETE CASCADE,
    CONSTRAINT uq_tipuri_bilete_eveniment UNIQUE (eveniment_id, nume),
    CONSTRAINT ck_tipuri_bilete_pret CHECK (pret >= 0),
    CONSTRAINT ck_tipuri_bilete_stoc_total CHECK (stoc_total >= 0),
    CONSTRAINT ck_tipuri_bilete_stoc_disp CHECK (stoc_disponibil >= 0 AND stoc_disponibil <= stoc_total)
);

CREATE TABLE locuri_eveniment (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    eveniment_id NUMBER NOT NULL,
    rand NUMBER(4) NOT NULL,
    coloana NUMBER(4) NOT NULL,
    cod VARCHAR2(20) NOT NULL,
    tip_bilet VARCHAR2(80) NOT NULL,
    status VARCHAR2(20) DEFAULT 'LIBER' NOT NULL,
    CONSTRAINT pk_locuri_eveniment PRIMARY KEY (id),
    CONSTRAINT fk_locuri_eveniment_eveniment FOREIGN KEY (eveniment_id) REFERENCES evenimente(id) ON DELETE CASCADE,
    CONSTRAINT fk_locuri_eveniment_tip FOREIGN KEY (eveniment_id, tip_bilet) REFERENCES tipuri_bilete_eveniment(eveniment_id, nume),
    CONSTRAINT uq_locuri_eveniment_cod UNIQUE (eveniment_id, cod),
    CONSTRAINT uq_locuri_eveniment_pozitie UNIQUE (eveniment_id, rand, coloana),
    CONSTRAINT ck_locuri_eveniment_status CHECK (status IN ('LIBER', 'VANDUT', 'INEXISTENT')),
    CONSTRAINT ck_locuri_eveniment_pozitie CHECK (rand >= 0 AND coloana >= 0)
);

CREATE TABLE bilete (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    tip VARCHAR2(20) NOT NULL,
    cod_bilet VARCHAR2(50) NOT NULL,
    eveniment_id NUMBER NOT NULL,
    client_id NUMBER NOT NULL,
    seat_code VARCHAR2(20),
    tip_bilet VARCHAR2(80) NOT NULL,
    pret NUMBER(10, 2) NOT NULL,
    status VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_bilete PRIMARY KEY (id),
    CONSTRAINT uq_bilete_cod UNIQUE (cod_bilet),
    CONSTRAINT fk_bilete_eveniment FOREIGN KEY (eveniment_id) REFERENCES evenimente(id),
    CONSTRAINT fk_bilete_client FOREIGN KEY (client_id) REFERENCES utilizatori(id),
    CONSTRAINT fk_bilete_tip FOREIGN KEY (eveniment_id, tip_bilet) REFERENCES tipuri_bilete_eveniment(eveniment_id, nume),
    CONSTRAINT fk_bilete_loc FOREIGN KEY (eveniment_id, seat_code) REFERENCES locuri_eveniment(eveniment_id, cod),
    CONSTRAINT ck_bilete_tip CHECK (tip IN ('CU_LOC', 'FARA_LOC')),
    CONSTRAINT ck_bilete_status CHECK (status IN ('PLATIT', 'FOLOSIT', 'ANULAT')),
    CONSTRAINT ck_bilete_pret CHECK (pret >= 0),
    CONSTRAINT ck_bilete_loc CHECK (
        (tip = 'CU_LOC' AND seat_code IS NOT NULL)
        OR (tip = 'FARA_LOC' AND seat_code IS NULL)
    )
);

CREATE TABLE comenzi (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    client_id NUMBER NOT NULL,
    total NUMBER(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_comenzi PRIMARY KEY (id),
    CONSTRAINT fk_comenzi_client FOREIGN KEY (client_id) REFERENCES utilizatori(id),
    CONSTRAINT ck_comenzi_total CHECK (total >= 0)
);

CREATE TABLE comanda_bilete (
    comanda_id NUMBER NOT NULL,
    bilet_id NUMBER NOT NULL,
    CONSTRAINT pk_comanda_bilete PRIMARY KEY (comanda_id, bilet_id),
    CONSTRAINT fk_comanda_bilete_comanda FOREIGN KEY (comanda_id) REFERENCES comenzi(id) ON DELETE CASCADE,
    CONSTRAINT fk_comanda_bilete_bilet FOREIGN KEY (bilet_id) REFERENCES bilete(id),
    CONSTRAINT uq_comanda_bilete_bilet UNIQUE (bilet_id)
);

CREATE TABLE agent_event_assignments (
    agent_id NUMBER NOT NULL,
    eveniment_id NUMBER NOT NULL,
    assigned_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_agent_event_assignments PRIMARY KEY (agent_id, eveniment_id),
    CONSTRAINT fk_agent_assignments_agent FOREIGN KEY (agent_id) REFERENCES utilizatori(id),
    CONSTRAINT fk_agent_assignments_eveniment FOREIGN KEY (eveniment_id) REFERENCES evenimente(id) ON DELETE CASCADE
);

CREATE INDEX idx_evenimente_locatie ON evenimente(locatie_id);
CREATE INDEX idx_evenimente_organizator ON evenimente(organizator_id);
CREATE INDEX idx_bilete_eveniment ON bilete(eveniment_id);
CREATE INDEX idx_bilete_client ON bilete(client_id);
CREATE INDEX idx_comenzi_client ON comenzi(client_id);
